"""Add product_type and other missing columns to Product table

Revision ID: 004b66118bc7
Revises: 
Create Date: 2025-06-16 12:13:18.175383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004b66118bc7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_method', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('delivery_data', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('auto_delivery', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_info', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('delivery_info')

    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('category')
        batch_op.drop_column('auto_delivery')
        batch_op.drop_column('delivery_data')
        batch_op.drop_column('delivery_method')
        batch_op.drop_column('product_type')

    # ### end Alembic commands ###
