yarnPath: ".yarn/releases/yarn-4.4.0.cjs"
nodeLinker: node-modules

npmScopes:
  asu:
    npmRegistryServer: "https://npm.pkg.github.com"
    npmAlwaysAuth: true
    npmAuthToken: "${NPM_AUTH_TOKEN}"
